version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  spinnaker: sandbox/spinnaker@dev:alpha
  orb-tools: circleci/orb-tools@8.27.3

parameters:
  run-integration-tests:
    type: boolean
    default: false
  cluster-name:
    type: string
    default: "my-eks-tests"
    #default: "spinnaker-orb-tests"

jobs:
  trigger-integration-tests:
    executor: spinnaker/default
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - run:
          name: Trigger integration workflow
          command: |
            curl -u ${CIRCLE_TOKEN}: -X POST --header "Content-Type: application/json" -d "{
              \"branch\": \"${CIRCLE_BRANCH}\",
              \"parameters\": {
                \"cluster-name\": \"<< parameters.cluster-name >>\",
                \"run-integration-tests\": true
              }
            }" "https://circleci.com/api/v2/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pipeline"
  test-spinnaker:
    executor: spinnaker/default
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - spinnaker/install-spin:
          configure-spin: true
          generate-config: true
      - spinnaker/set-up-port-forwarding:
          pod: deck
          namespace: spinnaker
      - spinnaker/set-up-port-forwarding:
          pod: gate
          namespace: spinnaker
      - run:
          name: Test spin
          command: |
            # Wait for port forwarding to be set up
            sleep 30
            spin application list
      - spinnaker/trigger-pipeline-with-webhook:
          webhook-endpoint: "http://localhost:8084/webhooks/webhook/myappwebhook"
          payload: '{"status": "success", "message": "I\u0027ve got this" }'

workflows:
  lint-pack_validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: sandbox/spinnaker
          requires:
            - orb-tools/pack
          context: orb-publishing
      - trigger-integration-tests:
          cluster-name: << pipeline.parameters.cluster-name >>
          requires:
            - orb-tools/publish-dev
          context: orb-publishing

  integration-tests:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - test-spinnaker:
          cluster-name: << pipeline.parameters.cluster-name >>
